Inventory.web/Controllers/BillTypesController.cs
using Inventory.Services.BillTypeService;
using Inventory.ViewModel.Bill;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Runtime.InteropServices;

namespace Inventory.web.Controllers
{
    public class BillTypesController : Controller
    {
        private IBillTypeRepo _BillTypeRepo;

        public BillTypesController(IBillTypeRepo billTypeRepo)
        {
            _BillTypeRepo = billTypeRepo;
        }
        [HttpGet]
        public async Task< IActionResult> Index(int pageSize =10,int pageNumber=1)
        {
            var billTypes = await _BillTypeRepo.GetAll( pageNumber, pageSize);
            return View(billTypes);
        }
        [HttpGet]
        public IActionResult Create() 
        { return View(); }
        [HttpPost]
        public async Task<IActionResult>Create(CreateBillTypeViewmodel model)
        {
            if (ModelState.IsValid)
            {
                await _BillTypeRepo.Add(model);
               return  RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet ]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _BillTypeRepo.GetById(id);
            if (result == null) 
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost ]
        public async Task<IActionResult> Edit(BillTypeViewModel model, int id)
        {
          if (ModelState.IsValid)
            {
              await _BillTypeRepo.Update(model, id);
                 return   RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet ]
        public async Task<IActionResult>Delete(int id)
        {
            await _BillTypeRepo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Inventory.web/Controllers/CustomerTypeController.cs
using Inventory.Repository.customerTypes;
using Inventory.Services.BillTypeService;
using Inventory.ViewModel.Bill;
using Inventory.ViewModel.UserCustomerType;
using Microsoft.AspNetCore.Mvc;

namespace Inventory.web.Controllers
{
    public class CustomerTypeController : Controller
    {
        private readonly ICustomerTypeRepo _customerTypeRepo;
        public CustomerTypeController(ICustomerTypeRepo customerTypeRepo)
        {
            _customerTypeRepo = customerTypeRepo;
        }
        [HttpGet]
        public async Task<IActionResult> Index(int pageSize = 10, int pageNumber = 1)
        {
            var customerTypes = await _customerTypeRepo.GetAll(pageNumber, pageSize);
            return View(customerTypes);
        }
        [HttpGet]
        public IActionResult Create()
        { return View(); }
        [HttpPost]
        public async Task<IActionResult> Create(CustomerTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _customerTypeRepo.Add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _customerTypeRepo.GetById(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CustomerTypeViewModel model,int id)
        {
            if (ModelState.IsValid)
            {
                await _customerTypeRepo.Update(model, id);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _customerTypeRepo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Inventory.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventory Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EFCoreWithAsp.netCore.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">Inventory Management system</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link align-middle px-0 text-white">
                                <i class="fs-4 bi bi-house-fill"></i><span class="ms-1 d-none d-sm-inline">Home</span>
                            </a>
                        </li>

                        <li>
                            <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle text-white">
                                <i class="fs-4 bi bi-people-fill"></i><span class="ms-1 d-none d-sm-inline">BillTypes</span>
                            </a>
                            <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                                <li class="w-100">
                                    <a asp-controller="BillTypes" asp-action="Index" class="nav-link px-0 text-white"> Bill Types</a>
                                </li>
                                <li>
                                    <a asp-controller="CustomerType" asp-action="Index" class="nav-link px-0 text-white"> Customer Types </a>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle text-white">
                                <i class="fs-4 bi bi-building-fill-gear"></i><span class="ms-1 d-none d-sm-inline">Department</span>
                            </a>
                            <ul class="collapse show nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                                <li class="w-100">
                                    <a asp-controller="Department" asp-action="Index" class="nav-link px-0 text-white"> List all</a>
                                </li>
                                <li>
                                    <a asp-controller="Department" asp-action="Add" class="nav-link px-0 text-white"> Add Department </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <hr>

                </div>
            </div>
            <div class="col py-3">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EFCoreWithAsp.netCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>